# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OCaml Labs
email: gg417@cl.cam.ac.uk  sk826@cl.cam.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  OCaml Labs is an initiative within the Cambridge Computer Laboratory started by Anil Madhavapeddy in 2011 to promote research, growth and collaboration within the wider OCaml community.
baseurl: ""
url: "https://ocamllabs.github.io/"

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - script
  - Dockerfile
  - .travis.yml

markdown: kramdown
kramdown:
  input: GFM

collections:
  authors:
  roles:
  papers:
  talks:
  events:
  doc:
   output: true
  releases:
   output: true

responsive_image:
  template: _includes/responsive-image.html
  default_quality: 90
  sizes:
    - width: 190
      quality: 80
    - width: 1400
  base_path: assets
  output_path_format: assets/resized/%{width}/%{basename}
  
